@startuml connect_and_create_table
hide footbox
!theme plain
box "Client"
    participant "User Network\n1" as User1
    participant "Table Network\n1" as Table1
end box

box "Server"
    participant "User Manager"
    participant "Table Manager"
end box

skinparam sequenceMessageAlign direction
skinparam lifelineStrategy dashed

User1->>"User Manager":<back:#FFFFFF>OnClientConnected()</back>
activate "User Manager"
"User Manager"->>User1:<back:#FFFFFF>SetUserId(0)
"User Manager"->"Table Manager":<back:#FFFFFF>AddToAvailableTable(uId)

activate "Table Manager"


"Table Manager"-->>Table1 **:Spawn()
Table1->>User1:CreateTableReplica()
"Table Manager"-->>"User Manager":(tId, seat)
deactivate "Table Manager"
"User Manager"->>User1:<back:#FFFFFF>MoveUserToTableClientRpc(tId, seat)

deactivate "User Manager"
@enduml