@startuml table_join
hide footbox
!theme plain
!pragma teoz true
skinparam sequenceMessageAlign direction
skinparam lifelineStrategy dashed

box Client
    participant "User Network\n2" as User1
    participant "Table Network\n1" as Table1
    participant "Table Network\n2" as Table2
end box

Box Server
    participant "User Manager" as UserM
    participant "Table Manager" as TableM
end box

User1->>UserM ++:<back:#FFFFFF>MoveUserToTableRpc(uId, tId)
UserM->TableM ++:<back:#FFFFFF>MoveUserToTable(uId, tId)
TableM->>Table1 ++:<back:#FFFFFF>RemoveFromTable(uId)
Table1->>User1 --:<back:#ffffff>DettachUserTableReplica()
opt Table 1 is empty
    TableM-->>Table1 ++:<back:#FFFFFF>Despawn()
    Table1-->>User1:<back:#ffffff>RemoveTableReplica()
    destroy Table1
end
TableM->>Table2 ++:<back:#FFFFFF>AddToTable(uId)
Table2->>User1 --:<back:#ffffff>AttachUserTableReplica()
TableM-->>UserM --:<back:#ffffff>(tId, seat)
UserM->>User1 --:<back:#ffffff>MoveUserToTableClientRpc(tId, seat)
@enduml